//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProxy.h"

@interface _APSecurityUtilImpl : NSProxy
{
}

+ (CDStruct_e6af4fdc *)shared;

@end

