//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface _TBIUDituInfo : NSObject
{
    NSString *_result;
    double _offsetPosx;
    double _offsetPosy;
}

- (void).cxx_destruct;
- (BOOL)isSuccess;
@property(nonatomic) double offsetPosx; // @synthesize offsetPosx=_offsetPosx;
@property(nonatomic) double offsetPosy; // @synthesize offsetPosy=_offsetPosy;
@property(retain, nonatomic) NSString *result; // @synthesize result=_result;

@end

