//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ABTestView : NSObject
{
    NSString *_Width;
    NSString *_Height;
    NSString *_x;
    NSString *_y;
    NSString *_backgroundColor;
    NSString *_alpha;
    NSString *_tag;
    NSString *_name;
    NSString *_nameType;
    NSString *_visibility;
    NSString *_userInteractionEnabled;
    NSString *_actionURL;
    NSString *_abTestId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *Height; // @synthesize Height=_Height;
@property(retain, nonatomic) NSString *Width; // @synthesize Width=_Width;
@property(retain, nonatomic) NSString *abTestId; // @synthesize abTestId=_abTestId;
@property(retain, nonatomic) NSString *actionURL; // @synthesize actionURL=_actionURL;
@property(retain, nonatomic) NSString *alpha; // @synthesize alpha=_alpha;
@property(retain, nonatomic) NSString *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (id)initWithDictionary:(id)arg1 error:(id *)arg2;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *nameType; // @synthesize nameType=_nameType;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSString *userInteractionEnabled; // @synthesize userInteractionEnabled=_userInteractionEnabled;
@property(retain, nonatomic) NSString *visibility; // @synthesize visibility=_visibility;
@property(retain, nonatomic) NSString *x; // @synthesize x=_x;
@property(retain, nonatomic) NSString *y; // @synthesize y=_y;

@end

