//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABTestView.h"

@class NSString;

@interface ABTestButton : ABTestView
{
    NSString *_title;
    NSString *_titleColor;
    NSString *_image;
    NSString *_type;
    NSString *_padding;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *padding; // @synthesize padding=_padding;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *titleColor; // @synthesize titleColor=_titleColor;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;

@end

