//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABTestView.h"

@class NSString;

@interface ABTestImageView : ABTestView
{
    NSString *_image;
    NSString *_contentMode;
    NSString *_imageUrl;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *contentMode; // @synthesize contentMode=_contentMode;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;

@end

