//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABTestView.h"

@class NSString;

@interface ABTestLabel : ABTestView
{
    NSString *_textColor;
    NSString *_fontSize;
    NSString *_text;
    NSString *_align;
    NSString *_numberOfLines;
    NSString *_lineBreakMode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *align; // @synthesize align=_align;
@property(retain, nonatomic) NSString *fontSize; // @synthesize fontSize=_fontSize;
@property(retain, nonatomic) NSString *lineBreakMode; // @synthesize lineBreakMode=_lineBreakMode;
@property(retain, nonatomic) NSString *numberOfLines; // @synthesize numberOfLines=_numberOfLines;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSString *textColor; // @synthesize textColor=_textColor;

@end

