//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ABTestTaskModel, NSDictionary, NSMutableDictionary, NSMutableString, NSObject<OS_dispatch_queue>, NSString;

@interface ABTestEngine : NSObject
{
    NSString *_groupConfig;
    ABTestTaskModel *_taskModel;
    ABTestTaskModel *_matchedModel;
    NSObject<OS_dispatch_queue> *_queue;
    NSString *_appKey;
    NSString *_groupName;
    NSMutableDictionary *_btsNameSelDic;
    NSMutableDictionary *_btsNameIMPDic;
    NSMutableDictionary *_aSelectorBtsNameDic;
    NSMutableDictionary *_bSelectorBtsNameDic;
    NSMutableDictionary *_selectorBucketNameDic;
    NSString *_className;
    NSString *_pageName;
    NSDictionary *_argsDic;
    id _dynamicEngine;
    NSMutableString *_testTrack;
}

+ (void)persistABTestTaskWithGroupDic:(id)arg1;
+ (void)persistABTestTaskWithGroupDic:(id)arg1 withGroupName:(id)arg2;
+ (void)requestABTEstTaskWithConfigGroup:(id)arg1;
+ (void)requestABTestTaskWithAppVersion:(id)arg1;
+ (void)requestABTestTaskWithGroupName:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *aSelectorBtsNameDic; // @synthesize aSelectorBtsNameDic=_aSelectorBtsNameDic;
- (SEL)aSelectorWithSelector:(SEL)arg1 forBtsName:(id)arg2;
@property(copy, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(retain, nonatomic) NSDictionary *argsDic; // @synthesize argsDic=_argsDic;
@property(retain, nonatomic) NSMutableDictionary *bSelectorBtsNameDic; // @synthesize bSelectorBtsNameDic=_bSelectorBtsNameDic;
- (SEL)bSelectorWithSelector:(SEL)arg1 forBtsName:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *btsNameIMPDic; // @synthesize btsNameIMPDic=_btsNameIMPDic;
@property(retain, nonatomic) NSMutableDictionary *btsNameSelDic; // @synthesize btsNameSelDic=_btsNameSelDic;
- (id)bucketNameWithGroupName:(id)arg1 btsName:(id)arg2;
@property(retain, nonatomic) NSString *className; // @synthesize className=_className;
- (void)commitEventWithBucketName:(id)arg1 forBtsName:(id)arg2;
@property(retain, nonatomic) id dynamicEngine; // @synthesize dynamicEngine=_dynamicEngine;
- (void)forcedRegisterGroupName:(id)arg1;
@property(copy, nonatomic) NSString *groupConfig; // @synthesize groupConfig=_groupConfig;
- (id)groupConfigDataForGroupName:(id)arg1;
- (id)groupConfigWithGroupName:(id)arg1 btsName:(id)arg2;
@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
- (CDUnknownFunctionPointerType)impForBtsName:(id)arg1;
- (id)init;
- (BOOL)isSameDay:(id)arg1;
@property(retain, nonatomic) ABTestTaskModel *matchedModel; // @synthesize matchedModel=_matchedModel;
@property(retain, nonatomic) NSString *pageName; // @synthesize pageName=_pageName;
- (id)parseTaskJson:(id)arg1;
- (void)parseTaskWithGroupName:(id)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)recordABLogWithMatchedBucketName:(id)arg1 forBtsName:(id)arg2;
- (void)recordPerformBucketName:(id)arg1 forBtsName:(id)arg2;
- (void)recordPerformDate;
- (void)registerABTestSelector:(SEL)arg1 aSelector:(SEL)arg2 bSelector:(SEL)arg3 forBtsName:(id)arg4;
- (void)registerABTestSelector:(SEL)arg1 forBtsName:(id)arg2;
- (void)registerABTestSelector:(SEL)arg1 forBucketName:(id)arg2 btsName:(id)arg3;
- (BOOL)registerGroupName:(id)arg1;
- (void)runABTest:(id)arg1 baseline:(CDUnknownBlockType)arg2 variations:(id)arg3;
- (void)runWithObject:(id)arg1 forBtsName:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *selectorBucketNameDic; // @synthesize selectorBucketNameDic=_selectorBucketNameDic;
- (SEL)selectorForBtsName:(id)arg1;
- (SEL)selectorWithBucketName:(id)arg1 forBtsName:(id)arg2;
@property(retain, nonatomic) ABTestTaskModel *taskModel; // @synthesize taskModel=_taskModel;
@property(copy, nonatomic) NSMutableString *testTrack; // @synthesize testTrack=_testTrack;
- (void)showDebugLog;
- (id)taskModelForBtsName:(id)arg1;

@end

