//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface ACRichTextComponent : NSObject
{
    NSString *_text;
    NSString *_tagLabel;
    NSMutableDictionary *_attributes;
    int _position;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *attributes; // @synthesize attributes=_attributes;
- (id)initWithText:(id)arg1 attributes:(id)arg2;
@property(nonatomic) int position; // @synthesize position=_position;
@property(copy, nonatomic) NSString *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;

@end

