//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UIScrollView;

__attribute__((visibility("hidden")))
@interface FMFloatView : UIView
{
    BOOL _needBgBlur;
    BOOL _animated;
    BOOL _isShowing;
    UIScrollView *_container;
    UIImageView *_blurBgView;
    UIButton *_closeButton;
    UIView *_dialog;
    float _floatViewAlpha;
    UIView *_floatViewSuperView;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL animated; // @synthesize animated=_animated;
@property(retain, nonatomic) UIImageView *blurBgView; // @synthesize blurBgView=_blurBgView;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIScrollView *container; // @synthesize container=_container;
@property(retain, nonatomic) UIView *dialog; // @synthesize dialog=_dialog;
- (void)doShow;
@property(nonatomic) float floatViewAlpha; // @synthesize floatViewAlpha=_floatViewAlpha;
@property(retain, nonatomic) UIView *floatViewSuperView; // @synthesize floatViewSuperView=_floatViewSuperView;
- (id)getScreenShot;
- (void)hideFloatView;
- (id)initFloatDialog;
- (id)initFloatTip;
- (id)initFloatView;
@property(nonatomic) BOOL isShowing; // @synthesize isShowing=_isShowing;
@property(nonatomic) BOOL needBgBlur; // @synthesize needBgBlur=_needBgBlur;
- (void)resetDialog:(struct CGSize)arg1;
- (void)showInView:(id)arg1;
- (void)showInView:(id)arg1 animated:(BOOL)arg2;

@end

