//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface FMFormModel : TBJSONModel
{
    NSString *_detailText;
    NSString *_selector;
    unsigned int _accessoryViewType;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int accessoryViewType; // @synthesize accessoryViewType=_accessoryViewType;
@property(copy, nonatomic) NSString *detailText; // @synthesize detailText=_detailText;
@property(copy, nonatomic) NSString *selector; // @synthesize selector=_selector;

@end

