//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class FMImageView, NSString, UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface FMForwardFlowGuideSheet : UIView
{
    CDUnknownBlockType _confirmBlock;
    BOOL isGuideDataNull;
    NSString *moreInfoUrl;
    UILabel *_titleLabel;
    FMImageView *_imgView;
    UILabel *_descLabel;
    UIButton *_moreInfoButton;
    UIView *_line;
    UIButton *_confirmButton;
}

- (void).cxx_destruct;
- (void)clickConfirmButton:(id)arg1;
- (void)clickMoreInfoButton:(id)arg1;
- (void)close;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
- (id)getSeparatedLinesFromLabel:(id)arg1;
@property(retain, nonatomic) FMImageView *imgView; // @synthesize imgView=_imgView;
- (id)init;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
- (void)loadDescLabel:(id)arg1;
- (void)loadSheetView:(id)arg1;
@property(retain, nonatomic) UIButton *moreInfoButton; // @synthesize moreInfoButton=_moreInfoButton;
- (void)setConfirmBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

