//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FMBaseTableViewCell.h"

@class KLSwitch, UIImageView;

__attribute__((visibility("hidden")))
@interface FMFormCell : FMBaseTableViewCell
{
    id <FMFormCellProtocol> _delegate;
    UIImageView *_markImageView;
    KLSwitch *_switchView;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak id <FMFormCellProtocol> delegate; // @synthesize delegate=_delegate;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
@property(retain, nonatomic) UIImageView *markImageView; // @synthesize markImageView=_markImageView;
- (void)setModel:(id)arg1;
@property(retain, nonatomic) KLSwitch *switchView; // @synthesize switchView=_switchView;

@end

