//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBMBDefaultPage.h"

@class FMFishpondDO, FMImageView, NSLayoutConstraint, NSMutableArray, UIButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface FMGeneralFishpondInfoView : TBMBDefaultPage
{
    struct CGRect _originFrame;
    NSLayoutConstraint *_constraint;
    FMImageView *_bannerImageView;
    UIImageView *_blurImageView;
    UIImageView *_layerView;
    FMImageView *_logoImageView;
    UILabel *_nameLabel;
    UILabel *_totalPopularityLabel;
    UILabel *_lastPopularityLabel;
    UILabel *_itemsCountLabel;
    FMImageView *_levelButton;
    UIButton *_usersContainerView;
    UILabel *_usersCountLabel;
    NSMutableArray *_userAvatarImageViewArray;
    FMFishpondDO *_fishpondDO;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FMImageView *bannerImageView; // @synthesize bannerImageView=_bannerImageView;
- (void)bind;
@property(retain, nonatomic) UIImageView *blurImageView; // @synthesize blurImageView=_blurImageView;
@property(retain, nonatomic) FMFishpondDO *fishpondDO; // @synthesize fishpondDO=_fishpondDO;
- (void)gotoUserList;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *itemsCountLabel; // @synthesize itemsCountLabel=_itemsCountLabel;
@property(retain, nonatomic) UILabel *lastPopularityLabel; // @synthesize lastPopularityLabel=_lastPopularityLabel;
@property(retain, nonatomic) UIImageView *layerView; // @synthesize layerView=_layerView;
- (void)layout;
@property(retain, nonatomic) FMImageView *levelButton; // @synthesize levelButton=_levelButton;
@property(retain, nonatomic) FMImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) struct CGRect originFrame; // @synthesize originFrame=_originFrame;
- (void)refreshDidScroll:(id)arg1;
@property(retain, nonatomic) UILabel *totalPopularityLabel; // @synthesize totalPopularityLabel=_totalPopularityLabel;
@property(copy, nonatomic) NSMutableArray *userAvatarImageViewArray; // @synthesize userAvatarImageViewArray=_userAvatarImageViewArray;
@property(retain, nonatomic) UIButton *usersContainerView; // @synthesize usersContainerView=_usersContainerView;
@property(retain, nonatomic) UILabel *usersCountLabel; // @synthesize usersCountLabel=_usersCountLabel;

@end

