//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIImageView;

__attribute__((visibility("hidden")))
@interface FMGroupChatUserHeadersView : UIView
{
    NSArray *_userIdsArray;
    id <FMGroupChatUserHeadersViewOnClicked> _delegate;
    UIImageView *_accessoryView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *accessoryView; // @synthesize accessoryView=_accessoryView;
- (void)addHeaders;
@property(nonatomic) __weak id <FMGroupChatUserHeadersViewOnClicked> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)removeHeaders;
@property(retain, nonatomic) NSArray *userIdsArray; // @synthesize userIdsArray=_userIdsArray;
- (void)updateConstraints;

@end

