//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RACSequence.h"

@class NSArray;

@interface RACArraySequence : RACSequence
{
    NSArray *_backingArray;
    unsigned int _offset;
}

+ (id)sequenceWithArray:(id)arg1 offset:(unsigned int)arg2;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *array;
@property(readonly, copy, nonatomic) NSArray *backingArray; // @synthesize backingArray=_backingArray;
- (unsigned int)countByEnumeratingWithState:(CDStruct_11f37819 *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)head;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) unsigned int offset; // @synthesize offset=_offset;
- (id)tail;

@end

