//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProxy.h"

@interface TBMBMessageProxy : NSProxy
{
    Class _proxyClass;
    unsigned int _key;
}

+ (void)__$$__NullMethod;
- (BOOL)conformsToProtocol:(id)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)initWithClass:(Class)arg1 andKey:(unsigned int)arg2;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)processInvocation:(id)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;

@end

