//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TBMBRxCommandProtocol.h"

@class NSString;

@interface TBMBRxCommand : NSObject <TBMBRxCommandProtocol>
{
}

+ (id)command;
- (id)_internalCreateSignal:(id)arg1 subscriber:(id)arg2;
- (id)createSignal:(id)arg1;
- (void)executeSubject:(id)arg1 andSubject:(id)arg2;
- (id)runScheduler;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

