//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet;

@protocol TBMBMessageReceiver <NSObject>
- (void)_$addObserver:(id)arg1;
- (NSSet *)_$listObserver;
- (void)_$removeObserver:(id)arg1;
- (void)handlerNotification:(id <TBMBNotification>)arg1;
- (NSSet *)listReceiveNotifications;
- (unsigned int)notificationKey;
@end

