//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDictionary, NSString;

@protocol TBMBNotification
- (id)body;
- (id <TBMBNotification>)createNextNotification:(NSString *)arg1;
- (id <TBMBNotification>)createNextNotification:(NSString *)arg1 withBody:(id)arg2;
- (id <TBMBNotification>)createNextNotificationForSEL:(SEL)arg1;
- (id <TBMBNotification>)createNextNotificationForSEL:(SEL)arg1 withBody:(id)arg2;
- (double)delay;
- (unsigned int)key;
- (id <TBMBNotification>)lastNotification;
- (NSString *)name;
- (unsigned int)retryCount;
- (void)setBody:(id)arg1;
- (void)setDelay:(double)arg1;
- (void)setKey:(unsigned int)arg1;
- (void)setLastNotification:(id <TBMBNotification>)arg1;
- (void)setRetryCount:(unsigned int)arg1;
- (void)setUserInfo:(NSDictionary *)arg1;
- (NSDictionary *)userInfo;
@end

