//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@protocol TBMBMessageSender
- (void)sendNotification:(NSString *)arg1;
- (void)sendNotification:(NSString *)arg1 body:(id)arg2;
- (void)sendNotificationForSEL:(SEL)arg1;
- (void)sendNotificationForSEL:(SEL)arg1 body:(id)arg2;
- (void)sendTBMBNotification:(id <TBMBNotification>)arg1;
@end

